export type Permission =
  | 'register_employee'
  | 'list_employees'
  | 'register_product'
  | 'edit_product'
  | 'delete_product'
  | 'delete_employee'
  | 'list_products'
  | 'register_order'
  | 'list_orders'
  | 'update_order_status'
