version: '3.8'

services:
  postgres:
    container_name: sweet-canteen-pg
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: sweet-canteen-db

  redis:
    container_name: sweet-canteen-redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=docker-redis
